package net.gegy1000.slyther.game;

public enum Skin {
    PURPLE_DEFAULT, BLUE_DEFAULT, CYAN_DEFAULT, LIME_DEFAULT, YELLOW_DEFAULT, ORANGE_DEFAULT, PINK_DEFAULT, RED_DEFAULT, MAGENTA_DEFAULT,
    AMERICA, BLUE_WHITE_RED_STRIPE, RED_BLACK_YELLOW_STRIPE, WHITE_RED_GREEN_STRIPE, WHITE_BLUE_RED_STRIPE, WHITE_RED_STRIPE, RAINBOW, YELLOW_BLUE_STRIPE, BLUE_WHITE_STRIPE, RED_WHITE_STRIPE, REDDIT, PURPLE_GREEN_STRIPE, YELLOW_GREEN_BLUE_STRIPE;
}
